# Set the version of Node.js to install (8.x", "10.x", "12.x", "13.x", etc.).
# Version numbers from Nodesource: https://github.com/nodesource/distributions
nodejs_version: "12.x"
donut_backend_repo: "https://github.com/ksraj123/social-platform-donut-backend.git"
donut_backend_repo_branch: "feature-ansible"
db_name: "donut-development"
