---

- name: Import the public key used by the package management system
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present

# - name: Add MongoDB repository
#   apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: install mongoDB
  apt: 
    name: mongodb
    state: present
    # update_cache: yes
  notify:
    - start mongodb

- name: copy config file
  copy:
    src: mongodb.conf
    dest: /etc/mongodb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mongodb

- name: Ensure mongodb is running and and enabled to start automatically on reboots
  systemd:
    name: mongodb
    enabled: yes
    state: started
